/**
 * AccessPage — Payment Guide & Access Request Form
 *
 * Public-facing enrollment page where students can:
 * - View 3 payment methods (Bank Islami, EasyPaisa, PayPal)
 * - Follow the step-by-step enrollment guide
 * - Submit an access request form
 * - Contact support via WhatsApp
 *
 * Redesigned to match the new landing page (src/routes/index.tsx, PR #44):
 * slate-neutral chrome, framer-motion reveals (prefers-reduced-motion aware),
 * gradient hero, two-track identity (Medical blue / Dental teal), unified
 * rounded-2xl cards, and lucide icons throughout.
 */

import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { motion, useReducedMotion } from "framer-motion";
import {
  Building2,
  Smartphone,
  CreditCard,
  CheckCircle2,
  ChevronRight,
  MessageCircle,
  AlertCircle,
  Sparkles,
  ArrowRight,
  Stethoscope,
  Smile,
  Info,
  TriangleAlert,
} from "lucide-react";
import { saveAccessRequest, type AccessRequest } from "../store/accessStore";
import { WhatsAppFloat } from "../components/WhatsAppFloat";

export const Route = createFileRoute("/access")({
  component: AccessPage,
});

// ─── Select Payment Methods ──────────────────────────────────────────────

interface PaymentDetail {
  label: string;
  value: string;
}

const PAYMENT_METHODS = [
  {
    id: "bank-islami",
    name: "Bank Islami",
    icon: Building2,
    tone: "text-blue-600 bg-blue-50",
    details: [
      { label: "Bank Name", value: "Bank Islami Pakistan LTD." },
      { label: "Account Title", value: "Ahsan Mahmood Khan" },
      { label: "Account Number", value: "PK98BKIP0303800235070201" },
      { label: "Amount", value: "20$ / 5500 PKR" },
    ] as PaymentDetail[],
    warning: "Transfer the enrollment fee of 20$ / 5500 PKR and capture your electronic transaction bank receipt.",
  },
  {
    id: "easypaisa",
    name: "EasyPaisa",
    icon: Smartphone,
    tone: "text-emerald-600 bg-emerald-50",
    details: [
      { label: "Account Name", value: "Ahsan Mahmood Khan" },
      { label: "Account Number", value: "03105265337" },
    ] as PaymentDetail[],
    warning: "Transfer 20$ / 5500 PKR to the wallet and enter the unique ID generated by EasyPaisa in the transaction field.",
  },
  {
    id: "paypal",
    name: "PayPal",
    icon: CreditCard,
    tone: "text-indigo-600 bg-indigo-50",
    details: [
      { label: "Account Title", value: "Ahsan Mahmood Khan" },
      { label: "Account Number", value: "333591114926" },
      { label: "Routing Number", value: "031101279" },
    ] as PaymentDetail[],
    warning: "International registration fee is $20 USD. Provide the generated PayPal receipt ID as your Transaction ID.",
  },
];

const ENROLLMENT_STEPS = [
  { number: "1", title: "Choose Payment Method", desc: "Select Bank Islami, EasyPaisa, or PayPal" },
  { number: "2", title: "Make Payment", desc: "Send the enrollment fee using the account details" },
  { number: "3", title: "Note Transaction ID", desc: "Save the transaction/reference ID from your payment" },
  { number: "4", title: "Submit Request Form", desc: "Fill in your details below with the transaction ID" },
  { number: "5", title: "Wait for Approval", desc: "Admin will verify and approve within 24 hours" },
  { number: "6", title: "Start Learning!", desc: "Use your phone number to log in and access the EHR simulator" },
];

// ─── Component ────────────────────────────────────────────────────

function AccessPage() {
  const reduceMotion = useReducedMotion();

  // Shared reveal preset — collapses to no-op under prefers-reduced-motion.
  const rise = (i = 0) => ({
    initial: { opacity: 0, y: reduceMotion ? 0 : 20 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, amount: 0.15 },
    transition: { duration: reduceMotion ? 0 : 0.5, delay: reduceMotion ? 0 : i * 0.06 },
  });

  const [formData, setFormData] = useState({
    fullName: "",
    phone: "",
    email: "",
    paymentMethod: "easypaisa" as AccessRequest["paymentMethod"],
    transactionId: "",
  });
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");
  const [hasConfirmedReceipt, setHasConfirmedReceipt] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    // Basic validation
    if (!formData.fullName.trim() || !formData.phone.trim() || !formData.transactionId.trim()) {
      setError("Please fill in all required fields");
      return;
    }

    const request: AccessRequest = {
      id: `req-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      fullName: formData.fullName.trim(),
      phone: formData.phone.trim(),
      email: formData.email.trim(),
      paymentMethod: formData.paymentMethod,
      transactionId: formData.transactionId.trim(),
      submittedAt: new Date().toISOString(),
      status: "pending",
    };

    saveAccessRequest(request);
    // Generate a cross-device shareable request token
    const requestToken = btoa(JSON.stringify(request));
    (window as any).__lastRequestToken = requestToken;
    setSubmitted(true);
  };

  if (submitted) {
    return (
      <div className="flex min-h-dvh flex-col items-center justify-center overflow-x-hidden bg-slate-50 p-4 text-slate-800">
        <motion.div
          initial={{ opacity: 0, scale: reduceMotion ? 1 : 0.96, y: reduceMotion ? 0 : 16 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          transition={{ duration: reduceMotion ? 0 : 0.45 }}
          className="w-full max-w-md rounded-2xl border border-emerald-200 bg-white p-8 text-center shadow-lg shadow-emerald-500/5"
        >
          <div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-50">
            <CheckCircle2 className="h-9 w-9 text-emerald-500" />
          </div>
          <h2 className="text-xl font-bold text-slate-900">Request Submitted!</h2>
          <p className="mt-2 text-sm text-slate-500">
            Your access request has been received. An admin will review your payment and approve your account within 24 hours.
          </p>
          <div className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-500">
            Your Login ID: <span className="font-bold text-slate-900">{formData.phone}</span>
          </div>
          <Link
            to="/login"
            className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 px-6 py-2.5 text-sm font-semibold text-white transition hover:bg-slate-700"
          >
            Go to Login
            <ArrowRight className="h-4 w-4" />
          </Link>
          <p className="mt-3 text-xs text-slate-400">
            After submitting, message your name and phone on WhatsApp at +92 335 0340888 so the admin can approve your access.
          </p>
        </motion.div>
        <WhatsAppFloat />
      </div>
    );
  }

  return (
    <div className="min-h-dvh overflow-x-hidden bg-slate-50 text-slate-800">
      {/* Nav */}
      <nav className="sticky top-0 z-20 flex items-center justify-between border-b border-slate-200/70 bg-white/85 px-4 py-3 backdrop-blur-md">
        <img
          src="/healthcarehustlers-logo.png"
          alt="Healthcare Hustlers"
          className="h-7 w-auto"
          style={{ maxWidth: "160px" }}
        />
        <div className="flex items-center gap-2 text-xs">
          <Link to="/login" className="rounded-lg border border-slate-200 px-3 py-1.5 font-medium text-slate-600 hover:bg-slate-50">
            Student Login
          </Link>
          <Link to="/" className="rounded-lg bg-slate-900 px-3 py-1.5 font-medium text-white hover:bg-slate-700">
            Home
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative isolate overflow-hidden">
        {/* Subtle animated background */}
        <div className="pointer-events-none absolute inset-0 -z-10" aria-hidden="true">
          <motion.div
            className="absolute -top-24 left-1/2 h-[420px] w-[420px] -translate-x-[130%] rounded-full bg-blue-300/30 blur-3xl"
            animate={reduceMotion ? undefined : { x: [0, 48, 0], y: [0, 24, 0] }}
            transition={{ duration: 15, repeat: Infinity, repeatType: "mirror", ease: "easeInOut" }}
          />
          <motion.div
            className="absolute -top-16 left-1/2 h-[380px] w-[380px] translate-x-[20%] rounded-full bg-teal-300/30 blur-3xl"
            animate={reduceMotion ? undefined : { x: [0, -48, 0], y: [0, 32, 0] }}
            transition={{ duration: 17, repeat: Infinity, repeatType: "mirror", ease: "easeInOut" }}
          />
          <div className="absolute bottom-0 left-1/3 h-[300px] w-[300px] -translate-x-1/2 rounded-full bg-indigo-200/20 blur-3xl" />
        </div>

        <div className="mx-auto max-w-5xl px-4 pb-14 pt-14 text-center md:pt-20">
          <motion.p {...rise(0)} className="mx-auto mb-4 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white/70 px-3 py-1 text-xs font-medium text-slate-500">
            <Sparkles className="h-3.5 w-3.5 text-blue-500" />
            One enrollment — Medical + Dental revenue-cycle training
          </motion.p>

          <motion.h1 {...rise(1)} className="mx-auto max-w-3xl text-4xl font-extrabold tracking-tight text-slate-900 md:text-6xl">
            Enroll in the{" "}
            <span className="bg-gradient-to-r from-blue-600 to-teal-600 bg-clip-text text-transparent">
              EHR Simulation Portal
            </span>
          </motion.h1>

          <motion.p {...rise(2)} className="mx-auto mt-5 max-w-2xl text-base text-slate-500 md:text-lg">
            Pay once and get hands-on practice across the full clinical-to-financial workflow — medical
            billing and the dental RCM track, in one login.
          </motion.p>

          <motion.div {...rise(3)} className="mt-8 flex flex-wrap justify-center gap-3">
            <a
              href="#access-form"
              className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-7 py-3.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 transition hover:-translate-y-0.5 hover:bg-blue-700 hover:shadow-xl"
            >
              Enroll Now — 20$ / 5500 PKR
              <ArrowRight className="h-4 w-4" />
            </a>
            <Link
              to="/login"
              className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-7 py-3.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
            >
              Student Login
            </Link>
          </motion.div>
          <motion.p {...rise(4)} className="mt-4 text-center text-xs text-slate-400">
            One fee unlocks both the medical and dental RCM tracks
          </motion.p>

          {/* Two-track hero — what's included */}
          <div className="mt-12 grid grid-cols-1 gap-5 md:grid-cols-2">
            <motion.div {...rise(5)} className="relative overflow-hidden rounded-2xl border border-blue-200 bg-white p-6 text-left shadow-sm">
              <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-blue-600 to-blue-400" />
              <div className="flex items-center gap-3">
                <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
                  <Stethoscope className="h-6 w-6" />
                </span>
                <div>
                  <p className="text-[10px] font-bold uppercase tracking-widest text-blue-500">Medical track</p>
                  <h3 className="text-lg font-bold text-slate-900">Medical RCM Pipeline</h3>
                </div>
              </div>
              <ul className="mt-4 space-y-2 text-sm text-slate-600">
                {["Scribe → Coder → Prior Auth → Biller → AR Voice", "ICD-10 / CPT coding & CMS-1500 claims", "AI voice simulation for denial follow-up"].map((line) => (
                  <li key={line} className="flex items-start gap-2">
                    <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-blue-500" />
                    {line}
                  </li>
                ))}
              </ul>
            </motion.div>

            <motion.div {...rise(6)} className="relative overflow-hidden rounded-2xl border border-teal-200 bg-white p-6 text-left shadow-sm">
              <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-teal-600 to-emerald-400" />
              <div className="flex items-center gap-3">
                <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-teal-600">
                  <Smile className="h-6 w-6" />
                </span>
                <div>
                  <p className="text-[10px] font-bold uppercase tracking-widest text-teal-500">Dental track</p>
                  <h3 className="text-lg font-bold text-slate-900">Dental Billing & RCM</h3>
                </div>
              </div>
              <ul className="mt-4 space-y-2 text-sm text-slate-600">
                {["CDT coding with tooth / surface / quadrant", "Odontogram + perio chart & ADA claim form", "12-step adjudication, ledger & appeals"].map((line) => (
                  <li key={line} className="flex items-start gap-2">
                    <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-teal-500" />
                    {line}
                  </li>
                ))}
              </ul>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Enrollment steps */}
      <section className="mx-auto max-w-6xl px-4 pb-16">
        <motion.div {...rise(0)} className="mb-10 text-center">
          <p className="text-[11px] font-bold uppercase tracking-widest text-blue-600">Enrollment guide</p>
          <h2 className="mt-2 text-3xl font-bold text-slate-900">How to Enroll in 6 Steps</h2>
          <p className="mx-auto mt-3 max-w-2xl text-sm text-slate-500">From payment to your first log-in — the whole process, start to finish.</p>
        </motion.div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {ENROLLMENT_STEPS.map((step, i) => (
            <motion.div
              key={step.number}
              {...rise(i)}
              className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md"
            >
              <div className="flex items-start gap-3">
                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-blue-600 to-teal-500 text-base font-bold text-white shadow-sm transition group-hover:scale-105">
                  {step.number}
                </div>
                <div>
                  <h3 className="font-semibold text-slate-800">{step.title}</h3>
                  <p className="mt-1 text-xs text-slate-400">{step.desc}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Select payment method */}
      <section className="border-t border-slate-100 bg-white/60 py-16">
        <div className="mx-auto max-w-6xl px-4">
          <motion.div {...rise(0)} className="mb-10 text-center">
            <p className="text-[11px] font-bold uppercase tracking-widest text-teal-600">Payment</p>
            <h2 className="mt-2 text-3xl font-bold text-slate-900">Select a Payment Method</h2>
            <p className="mx-auto mt-3 max-w-2xl text-sm text-slate-500">Pick one, send the fee, then note your transaction ID for the form below.</p>
          </motion.div>

          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            {PAYMENT_METHODS.map((method, i) => {
              const Icon = method.icon;
              const selected = formData.paymentMethod === method.id;
              return (
                <motion.div
                  key={method.id}
                  {...rise(i)}
                  className={`group relative flex flex-col overflow-hidden rounded-2xl border-2 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg ${
                    selected ? "border-blue-500" : "border-slate-200 hover:border-slate-300"
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <span className={`flex h-11 w-11 items-center justify-center rounded-xl ${method.tone} transition group-hover:scale-110`}>
                      <Icon className="h-6 w-6" />
                    </span>
                    <span className="font-semibold text-slate-900">{method.name}</span>
                  </div>

                  <div className="mt-4 flex-1 space-y-2">
                    {method.details.map((d) => (
                      <div key={d.label} className="flex items-start justify-between gap-3 text-xs">
                        <span className="shrink-0 text-slate-400">{d.label}</span>
                        <span className="text-right font-medium text-slate-700">{d.value}</span>
                      </div>
                    ))}
                  </div>

                  <p className="mt-4 flex items-start gap-2 rounded-lg bg-amber-50 p-2.5 text-[11px] font-medium leading-relaxed text-amber-700">
                    <TriangleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                    {method.warning}
                  </p>

                  <button
                    onClick={() => setFormData({ ...formData, paymentMethod: method.id as AccessRequest["paymentMethod"] })}
                    className={`mt-4 w-full rounded-xl py-2 text-xs font-semibold transition-colors ${
                      selected
                        ? "bg-blue-600 text-white"
                        : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                    }`}
                  >
                    {selected ? "Selected" : "Select"}
                  </button>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Access request form */}
      <section id="access-form" className="py-16">
        <div className="mx-auto max-w-3xl px-4">
          <motion.div {...rise(0)} className="mb-8 text-center">
            <p className="text-[11px] font-bold uppercase tracking-widest text-blue-600">Step 4</p>
            <h2 className="mt-2 text-3xl font-bold text-slate-900">Access Request Form</h2>
            <p className="mx-auto mt-3 max-w-xl text-sm text-slate-500">Submit your details and transaction ID to request access.</p>
          </motion.div>

          <motion.div {...rise(1)} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8">
            <form onSubmit={handleSubmit} className="space-y-5">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-slate-600">Student Full Name *</label>
                  <input
                    type="text"
                    value={formData.fullName}
                    onChange={(e) => setFormData({ ...formData, fullName: e.target.value })}
                    placeholder="John Doe"
                    className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none transition focus:border-slate-400 focus:ring-1 focus:ring-slate-300"
                  />
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-slate-600">Phone Number (Login ID) *</label>
                  <input
                    type="tel"
                    value={formData.phone}
                    onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                    placeholder="03001234567"
                    className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none transition focus:border-slate-400 focus:ring-1 focus:ring-slate-300"
                  />
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-slate-600">Email</label>
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    placeholder="student@example.com"
                    className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none transition focus:border-slate-400 focus:ring-1 focus:ring-slate-300"
                  />
                </div>
                <div>
                  <label className="mb-1.5 block text-xs font-medium text-slate-600">Select Payment Method</label>
                  <select
                    value={formData.paymentMethod}
                    onChange={(e) =>
                      setFormData({ ...formData, paymentMethod: e.target.value as AccessRequest["paymentMethod"] })
                    }
                    className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none transition focus:border-slate-400 focus:ring-1 focus:ring-slate-300"
                  >
                    <option value="easypaisa">EasyPaisa</option>
                    <option value="bank-islami">Bank Islami</option>
                    <option value="paypal">PayPal</option>
                  </select>
                </div>
                <div className="md:col-span-2">
                  <label className="mb-1.5 block text-xs font-medium text-slate-600">Unique Transaction ID *</label>
                  <input
                    type="text"
                    value={formData.transactionId}
                    onChange={(e) => setFormData({ ...formData, transactionId: e.target.value })}
                    placeholder="Enter the transaction/reference ID from your payment"
                    className="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none transition focus:border-slate-400 focus:ring-1 focus:ring-slate-300"
                  />
                </div>
              </div>

              {/* Pricing Note */}
              <div className="rounded-xl border border-amber-200 bg-amber-50 p-3.5 text-xs text-amber-700">
                <p className="font-medium">
                  Note: $20 / 5,500 PKR gives you access to the whole revenue cycle — both the Medical
                  and Dental tracks. No separate fee for dental.
                </p>
              </div>

              {/* Cross-Device Access Note */}
              <div className="rounded-xl border border-slate-200 bg-slate-50 p-3.5 text-xs text-slate-600">
                <p className="flex items-center gap-1.5 font-medium text-slate-700">
                  <Info className="h-4 w-4" /> Cross-Device Access
                </p>
                <p className="mt-1">Your access is tied to your phone number, not a single device. Once an admin approves you, log in from any device with the same number.</p>
              </div>

              {/* WhatsApp Receipt Confirmation */}
              <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4">
                <p className="mb-2 text-xs font-medium text-emerald-800">
                  Send your payment receipt to our WhatsApp for verification:
                </p>
                <a
                  href="https://api.whatsapp.com/send/?phone=923350340888&text&type=phone_number&app_absent=0"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white transition-colors hover:bg-emerald-500"
                >
                  <MessageCircle className="h-3.5 w-3.5" />
                  Send Receipt on WhatsApp
                </a>
                <div className="mt-3">
                  <p className="mb-2 text-xs font-medium text-slate-600">
                    Have you sent the payment receipt to our WhatsApp number?
                  </p>
                  <div className="flex items-center gap-4">
                    <label className="flex cursor-pointer items-center gap-1.5">
                      <input
                        type="radio"
                        name="receiptConfirmed"
                        checked={hasConfirmedReceipt}
                        onChange={() => setHasConfirmedReceipt(true)}
                        className="h-4 w-4 accent-emerald-600"
                      />
                      <span className="text-xs text-slate-700">Yes</span>
                    </label>
                    <label className="flex cursor-pointer items-center gap-1.5">
                      <input
                        type="radio"
                        name="receiptConfirmed"
                        checked={!hasConfirmedReceipt}
                        onChange={() => setHasConfirmedReceipt(false)}
                        className="h-4 w-4 accent-red-400"
                      />
                      <span className="text-xs text-slate-700">No</span>
                    </label>
                  </div>
                </div>
              </div>

              {error && (
                <div className="flex items-center gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-600">
                  <AlertCircle className="h-4 w-4" />
                  {error}
                </div>
              )}

              <button
                type="submit"
                disabled={!hasConfirmedReceipt}
                className={`flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold text-white transition-colors ${
                  hasConfirmedReceipt
                    ? "bg-blue-600 hover:bg-blue-700"
                    : "cursor-not-allowed bg-slate-300"
                }`}
              >
                <ChevronRight className="h-4 w-4" />
                Submit Access Request
              </button>
            </form>
          </motion.div>
        </div>
      </section>

      {/* WhatsApp Support */}
      <section className="border-t border-slate-100 bg-white/60 py-16">
        <div className="mx-auto max-w-3xl px-4">
          <motion.div {...rise(0)} className="flex flex-col items-start gap-4 rounded-2xl border border-emerald-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center">
            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600">
              <MessageCircle className="h-6 w-6" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold text-slate-900">Need Help? Contact Support</h3>
              <p className="mt-1 text-sm text-slate-500">
                Have questions about payment or enrollment? Chat with us on WhatsApp.
              </p>
            </div>
            <a
              href="https://api.whatsapp.com/send/?phone=923350340888&text&type=phone_number&app_absent=0"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-emerald-500"
            >
              <MessageCircle className="h-4 w-4" />
              WhatsApp Support
            </a>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white/70 px-4 py-6 text-center text-xs text-slate-400">
        www.healthcarehustlers.org — Healthcare Hustlers EHR Simulation Portal
      </footer>

      <WhatsAppFloat />
    </div>
  );
}
