/**
 * ICD-10-CM Code Repository — Medical Coding Educational Content
 *
 * 50+ common diagnosis codes organized by chapter with full descriptions,
 * categories, reimbursement rates, and coding guidelines.
 *
 * Inspiration: AAPC / ICD-10-CM Official Guidelines
 */

export interface ICD10Code {
  code: string;
  description: string;
  chapter: string;
  category: string;
  medicareRate?: number;      // approximate Medicare national rate
  commercialRate?: number;     // approximate commercial payer rate
  notes?: string;              // coding guidelines / tips
  guidelines?: string[];       // official coding guidelines
  excludes1?: string[];        // mutually exclusive codes
  excludes2?: string[];        // separate condition codes
  codeFirst?: string;          // underlying etiology
  useAdditional?: string[];    // additional codes needed
  laterality?: "none" | "right" | "left" | "bilateral" | "unspecified";
}

export const ICD10_CODES: ICD10Code[] = [
  // ─── Endocrine ──────────────────────────────────────────────────
  {
    code: "E11.9",
    description: "Type 2 diabetes mellitus without complications",
    chapter: "Endocrine",
    category: "Diabetes",
    medicareRate: 78.50,
    commercialRate: 145.00,
    notes: "Most common DM2 code. Use additional code for insulin use (Z79.4) or oral hypoglycemics (Z79.84).",
    guidelines: ["Code diabetes type first (E10/E11/E13)", "Use additional code for manifestation"],
    useAdditional: ["Z79.4 (long-term insulin use)", "Z79.84 (oral antidiabetic drugs)"],
    laterality: "none",
  },
  {
    code: "E10.9",
    description: "Type 1 diabetes mellitus without complications",
    chapter: "Endocrine",
    category: "Diabetes",
    medicareRate: 82.30,
    commercialRate: 152.00,
    notes: "Autoimmune. Always requires insulin — code Z79.4 always.",
    useAdditional: ["Z79.4 (long-term insulin use)"],
    laterality: "none",
  },
  {
    code: "E78.5",
    description: "Hyperlipidemia, unspecified",
    chapter: "Endocrine",
    category: "Lipid disorders",
    medicareRate: 45.20,
    commercialRate: 88.00,
    notes: "Use more specific code when type known (E78.0-E78.4).",
    guidelines: ["Specify type: pure hypercholesterolemia (E78.0), hypertriglyceridemia (E78.1)"],
    laterality: "none",
  },
  {
    code: "E66.9",
    description: "Obesity, unspecified",
    chapter: "Endocrine",
    category: "Obesity",
    medicareRate: 52.10,
    commercialRate: 95.00,
    notes: "Code BMI from Z68.- when documented. Use additional code for severity.",
    useAdditional: ["Z68.3-Z68.4 (BMI codes)"],
    laterality: "none",
  },
  {
    code: "E03.9",
    description: "Hypothyroidism, unspecified",
    chapter: "Endocrine",
    category: "Thyroid",
    medicareRate: 48.75,
    commercialRate: 92.00,
    notes: "Congenital hypothyroidism is E03.0-E03.1.",
    laterality: "none",
  },
  {
    code: "E11.21",
    description: "Type 2 diabetes mellitus with diabetic nephropathy",
    chapter: "Endocrine",
    category: "Diabetes with complications",
    medicareRate: 112.40,
    commercialRate: 198.00,
    notes: "Code first the diabetic complication. Interstitial nephropathy in DM.",
    guidelines: ["DM with kidney complications", "Use additional code for CKD stage (N18.-)"],
    useAdditional: ["N18.- (CKD stage)", "Z79.4 or Z79.84"],
    laterality: "none",
  },
  {
    code: "E11.40",
    description: "Type 2 diabetes mellitus with neurological complications",
    chapter: "Endocrine",
    category: "Diabetes with complications",
    medicareRate: 108.30,
    commercialRate: 185.00,
    notes: "Diabetic neuropathy. Use additional code to identify specific neurological manifestation.",
    useAdditional: ["G63 (polyneuropathy in diseases classified elsewhere)"],
    laterality: "none",
  },

  // ─── Circulatory ────────────────────────────────────────────────
  {
    code: "I10",
    description: "Essential (primary) hypertension",
    chapter: "Circulatory",
    category: "Hypertension",
    medicareRate: 55.00,
    commercialRate: 105.00,
    notes: "Most common circulatory code. Differentiate from secondary HTN (I15.-).",
    guidelines: ["Do not code 'controlled' or 'uncontrolled' — only presence of HTN"],
    excludes1: ["I15.- (secondary hypertension)"],
    laterality: "none",
  },
  {
    code: "I50.9",
    description: "Heart failure, unspecified",
    chapter: "Circulatory",
    category: "Heart failure",
    medicareRate: 125.80,
    commercialRate: 225.00,
    notes: "Specify systolic vs diastolic when documented (I50.2x-I50.3x).",
    guidelines: ["Combine with I50.2x for systolic, I50.3x for diastolic"],
    laterality: "none",
  },
  {
    code: "I25.10",
    description: "Atherosclerotic heart disease of native coronary artery",
    chapter: "Circulatory",
    category: "CAD",
    medicareRate: 118.40,
    commercialRate: 210.00,
    notes: "ASHD of native arteries only (not bypass grafts).",
    excludes2: ["I25.7- (atherosclerosis of bypass graft)"],
    laterality: "none",
  },
  {
    code: "I48.91",
    description: "Unspecified atrial fibrillation",
    chapter: "Circulatory",
    category: "Arrhythmia",
    medicareRate: 98.60,
    commercialRate: 175.00,
    notes: "Use more specific code when type known (paroxysmal, persistent, chronic).",
    guidelines: ["Paroxysmal = I48.0, Persistent = I48.19, Chronic = I48.20"],
    laterality: "none",
  },
  {
    code: "I48.20",
    description: "Chronic atrial fibrillation",
    chapter: "Circulatory",
    category: "Arrhythmia",
    medicareRate: 105.20,
    commercialRate: 188.00,
    notes: "Longstanding persistent AFib. Requires anticoagulation management.",
    laterality: "none",
  },
  {
    code: "I25.2",
    description: "Old myocardial infarction",
    chapter: "Circulatory",
    category: "CAD",
    medicareRate: 95.40,
    commercialRate: 168.00,
    notes: "MI > 4 weeks ago. No current symptoms. Do NOT use for acute MI.",
    guidelines: ["Do not use if patient is being treated for current MI"],
    laterality: "none",
  },
  {
    code: "I50.22",
    description: "Chronic systolic heart failure",
    chapter: "Circulatory",
    category: "Heart failure",
    medicareRate: 135.60,
    commercialRate: 245.00,
    notes: "HF with reduced ejection fraction (HFrEF). LVEF ≤ 40%.",
    laterality: "none",
  },
  {
    code: "I50.32",
    description: "Chronic diastolic heart failure",
    chapter: "Circulatory",
    category: "Heart failure",
    medicareRate: 130.20,
    commercialRate: 238.00,
    notes: "HF with preserved ejection fraction (HFpEF). LVEF ≥ 50%.",
    laterality: "none",
  },

  // ─── Respiratory ────────────────────────────────────────────────
  {
    code: "J45.909",
    description: "Unspecified asthma, uncomplicated",
    chapter: "Respiratory",
    category: "Asthma",
    medicareRate: 62.30,
    commercialRate: 118.00,
    notes: "Specify severity (mild intermittent, mild persistent, etc.) when documented.",
    guidelines: ["Mild intermittent = J45.2x, Mild persistent = J45.3x, Moderate = J45.4x, Severe = J45.5x"],
    laterality: "none",
  },
  {
    code: "J44.9",
    description: "Chronic obstructive pulmonary disease, unspecified",
    chapter: "Respiratory",
    category: "COPD",
    medicareRate: 95.80,
    commercialRate: 175.00,
    notes: "Distinguish from asthma. COPD is chronic, progressive, not fully reversible.",
    excludes2: ["J45.- (asthma)"],
    laterality: "none",
  },
  {
    code: "J15.9",
    description: "Unspecified bacterial pneumonia",
    chapter: "Respiratory",
    category: "Pneumonia",
    medicareRate: 88.40,
    commercialRate: 162.00,
    notes: "Specify organism when known (e.g., J15.0 for Klebsiella, J15.1 for Pseudomonas).",
    laterality: "none",
  },
  {
    code: "J20.9",
    description: "Acute bronchitis, unspecified",
    chapter: "Respiratory",
    category: "Bronchitis",
    medicareRate: 55.20,
    commercialRate: 108.00,
    notes: "Typically viral. Differentiate from acute exacerbation of COPD.",
    laterality: "none",
  },
  {
    code: "J06.9",
    description: "Acute upper respiratory infection, unspecified",
    chapter: "Respiratory",
    category: "URI",
    medicareRate: 38.50,
    commercialRate: 75.00,
    notes: "Common cold. Most self-limiting viral URI.",
    laterality: "none",
  },
  {
    code: "J45.40",
    description: "Moderate persistent asthma",
    chapter: "Respiratory",
    category: "Asthma",
    medicareRate: 78.60,
    commercialRate: 142.00,
    notes: "Daily symptoms, nightly awakenings >1x/week, daily SABA use.",
    laterality: "none",
  },
  {
    code: "J44.1",
    description: "COPD with acute exacerbation",
    chapter: "Respiratory",
    category: "COPD",
    medicareRate: 118.40,
    commercialRate: 215.00,
    notes: "Acute worsening of COPD requiring treatment change.",
    laterality: "none",
  },

  // ─── Digestive ──────────────────────────────────────────────────
  {
    code: "K21.9",
    description: "Gastro-esophageal reflux disease without esophagitis",
    chapter: "Digestive",
    category: "GERD",
    medicareRate: 48.20,
    commercialRate: 92.00,
    notes: "If esophagitis present, use K21.0.",
    laterality: "none",
  },
  {
    code: "K57.30",
    description: "Diverticulosis of large intestine without perforation",
    chapter: "Digestive",
    category: "Diverticulosis",
    medicareRate: 62.50,
    commercialRate: 118.00,
    notes: "Diverticulosis = presence only. Diverticulitis = inflammation (K57.2x).",
    laterality: "none",
  },
  {
    code: "K59.00",
    description: "Constipation, unspecified",
    chapter: "Digestive",
    category: "Constipation",
    medicareRate: 35.80,
    commercialRate: 68.00,
    notes: "Chronic constipation = K59.09. Drug-induced = K59.04.",
    laterality: "none",
  },
  {
    code: "K29.50",
    description: "Chronic gastritis, unspecified",
    chapter: "Digestive",
    category: "Gastritis",
    medicareRate: 52.40,
    commercialRate: 98.00,
    notes: "H. pylori association common — use additional code B96.81 if present.",
    laterality: "none",
  },
  {
    code: "K35.80",
    description: "Acute appendicitis, unspecified",
    chapter: "Digestive",
    category: "Appendicitis",
    medicareRate: 142.60,
    commercialRate: 265.00,
    notes: "Acute appendicitis without mention of perforation. K35.2 = with perforation.",
    laterality: "none",
  },

  // ─── Musculoskeletal ────────────────────────────────────────────
  {
    code: "M54.5",
    description: "Low back pain",
    chapter: "Musculoskeletal",
    category: "Back pain",
    medicareRate: 42.30,
    commercialRate: 82.00,
    notes: "Mechanical low back pain. Differentiate from radiculopathy (M54.1x).",
    guidelines: ["Do not use with specific diagnosis (disc herniation, spinal stenosis)"],
    laterality: "none",
  },
  {
    code: "M17.9",
    description: "Osteoarthritis of knee, unspecified",
    chapter: "Musculoskeletal",
    category: "Osteoarthritis",
    medicareRate: 68.40,
    commercialRate: 128.00,
    notes: "Specify laterality (M17.0 = bilateral, M17.1 = unilateral right, M17.2 = unilateral left).",
    laterality: "bilateral",
  },
  {
    code: "M19.90",
    description: "Osteoarthritis of unspecified site",
    chapter: "Musculoskeletal",
    category: "Osteoarthritis",
    medicareRate: 55.20,
    commercialRate: 105.00,
    notes: "Unspecified site — use specific site code when known.",
    laterality: "unspecified",
  },
  {
    code: "M79.1",
    description: "Myalgia",
    chapter: "Musculoskeletal",
    category: "Pain",
    medicareRate: 32.50,
    commercialRate: 62.00,
    notes: "Muscle pain. Differentiate from fibromyalgia (M79.7).",
    laterality: "none",
  },
  {
    code: "M17.11",
    description: "Unilateral primary osteoarthritis, right knee",
    chapter: "Musculoskeletal",
    category: "Osteoarthritis",
    medicareRate: 72.30,
    commercialRate: 135.00,
    notes: "Right knee OA. Use M17.12 for left knee.",
    laterality: "right",
  },
  {
    code: "M25.561",
    description: "Pain in right knee",
    chapter: "Musculoskeletal",
    category: "Pain",
    medicareRate: 38.20,
    commercialRate: 72.00,
    notes: "Joint pain specific to right knee.",
    laterality: "right",
  },

  // ─── Genitourinary ──────────────────────────────────────────────
  {
    code: "N18.3",
    description: "Chronic kidney disease, stage 3 (moderate)",
    chapter: "Genitourinary",
    category: "CKD",
    medicareRate: 72.60,
    commercialRate: 138.00,
    notes: "GFR 30-59 mL/min. Most common CKD stage. Always code underlying cause.",
    guidelines: ["Code first underlying condition (DM, HTN)", "Use additional code for dialysis status (Z99.2)"],
    laterality: "none",
  },
  {
    code: "N18.4",
    description: "Chronic kidney disease, stage 4 (severe)",
    chapter: "Genitourinary",
    category: "CKD",
    medicareRate: 88.40,
    commercialRate: 165.00,
    notes: "GFR 15-29 mL/min. Pre-dialysis planning needed.",
    laterality: "none",
  },
  {
    code: "N18.5",
    description: "Chronic kidney disease, stage 5",
    chapter: "Genitourinary",
    category: "CKD",
    medicareRate: 108.20,
    commercialRate: 205.00,
    notes: "GFR < 15 mL/min. End stage renal disease. Code dialysis status.",
    useAdditional: ["Z99.2 (dialysis status)", "Z94.0 (kidney transplant status)"],
    laterality: "none",
  },
  {
    code: "N39.0",
    description: "Urinary tract infection, site not specified",
    chapter: "Genitourinary",
    category: "UTI",
    medicareRate: 48.50,
    commercialRate: 92.00,
    notes: "Most common UTI code. Specify organism when known.",
    laterality: "none",
  },

  // ─── Blood ──────────────────────────────────────────────────────
  {
    code: "D50.9",
    description: "Iron deficiency anemia, unspecified",
    chapter: "Blood",
    category: "Anemia",
    medicareRate: 52.30,
    commercialRate: 98.00,
    notes: "Most common anemia. Always investigate underlying cause (GI bleed, menorrhagia).",
    laterality: "none",
  },
  {
    code: "D64.9",
    description: "Anemia, unspecified",
    chapter: "Blood",
    category: "Anemia",
    medicareRate: 42.80,
    commercialRate: 82.00,
    notes: "Use only when type not specified. Prefer specific anemia code.",
    laterality: "none",
  },

  // ─── Z Codes ────────────────────────────────────────────────────
  {
    code: "Z23",
    description: "Encounter for immunization",
    chapter: "Z Codes",
    category: "Preventive",
    medicareRate: 28.00,
    commercialRate: 55.00,
    notes: "Well-child visit code. Use with vaccine product codes (e.g., 90619).",
    laterality: "none",
  },
  {
    code: "Z34.90",
    description: "Encounter for supervision of normal pregnancy",
    chapter: "Z Codes",
    category: "Pregnancy",
    medicareRate: 65.40,
    commercialRate: 125.00,
    notes: "Routine prenatal visit. Use with weeks of gestation (Z3A.-).",
    useAdditional: ["Z3A.- (weeks of gestation)"],
    laterality: "none",
  },
  {
    code: "Z79.4",
    description: "Long-term (current) use of insulin",
    chapter: "Z Codes",
    category: "Medication management",
    medicareRate: 0,
    commercialRate: 0,
    notes: "Always secondary to diabetes code. Do NOT use for gestational DM on insulin.",
    laterality: "none",
  },
  {
    code: "Z79.84",
    description: "Long-term (current) use of oral antidiabetic drugs",
    chapter: "Z Codes",
    category: "Medication management",
    medicareRate: 0,
    commercialRate: 0,
    notes: "Secondary code for DM on oral agents.",
    laterality: "none",
  },

  // ─── Symptoms ───────────────────────────────────────────────────
  {
    code: "R51",
    description: "Headache",
    chapter: "Symptoms",
    category: "Pain",
    medicareRate: 35.20,
    commercialRate: 68.00,
    notes: "Do NOT use when specific headache diagnosis is known (migraine = G43.-).",
    laterality: "none",
  },
  {
    code: "R10.9",
    description: "Unspecified abdominal pain",
    chapter: "Symptoms",
    category: "Pain",
    medicareRate: 38.60,
    commercialRate: 72.00,
    notes: "Specify site when possible (R10.0-R10.3).",
    laterality: "none",
  },
  {
    code: "R05",
    description: "Cough",
    chapter: "Symptoms",
    category: "Respiratory",
    medicareRate: 32.40,
    commercialRate: 62.00,
    notes: "Acute cough (< 3 weeks) vs chronic (> 8 weeks). Do not code with definitive diagnosis.",
    laterality: "none",
  },
  {
    code: "R11.2",
    description: "Nausea with vomiting, unspecified",
    chapter: "Symptoms",
    category: "GI symptoms",
    medicareRate: 35.80,
    commercialRate: 68.00,
    notes: "R11.0 = nausea only, R11.1 = vomiting only, R11.2 = both.",
    laterality: "none",
  },
  {
    code: "R53.1",
    description: "Weakness",
    chapter: "Symptoms",
    category: "General",
    medicareRate: 32.50,
    commercialRate: 62.00,
    notes: "Generalized weakness, not specific to a limb.",
    laterality: "none",
  },

  // ─── Mental ─────────────────────────────────────────────────────
  {
    code: "F41.9",
    description: "Anxiety disorder, unspecified",
    chapter: "Mental",
    category: "Anxiety",
    medicareRate: 58.40,
    commercialRate: 112.00,
    notes: "Generalized anxiety = F41.1, Panic disorder = F41.0.",
    laterality: "none",
  },
  {
    code: "F32.9",
    description: "Major depressive disorder, single episode, unspecified",
    chapter: "Mental",
    category: "Depression",
    medicareRate: 65.20,
    commercialRate: 125.00,
    notes: "Specify severity (F32.0-F32.3) when documented.",
    guidelines: ["Mild = F32.0, Moderate = F32.1, Severe without psychosis = F32.2"],
    laterality: "none",
  },
  {
    code: "F33.2",
    description: "Major depressive disorder, recurrent, severe without psychotic features",
    chapter: "Mental",
    category: "Depression",
    medicareRate: 82.60,
    commercialRate: 158.00,
    notes: "Recurrent episodes of severe depression. Requires ongoing management.",
    laterality: "none",
  },

  // ─── Infectious ─────────────────────────────────────────────────
  {
    code: "B34.9",
    description: "Viral infection, unspecified",
    chapter: "Infectious",
    category: "Viral",
    medicareRate: 28.40,
    commercialRate: 55.00,
    notes: "Use only when no specific viral diagnosis is documented.",
    laterality: "none",
  },
  {
    code: "J12.9",
    description: "Viral pneumonia, unspecified",
    chapter: "Infectious",
    category: "Pneumonia",
    medicareRate: 82.60,
    commercialRate: 155.00,
    notes: "COVID-19 pneumonia = U07.1, Influenza pneumonia = J10.0.",
    laterality: "none",
  },

  // ─── Injury ─────────────────────────────────────────────────────
  {
    code: "S06.0X9A",
    description: "Concussion without loss of consciousness, initial encounter",
    chapter: "Injury",
    category: "Head injury",
    medicareRate: 95.40,
    commercialRate: 178.00,
    notes: "Use 7th character: A = initial, D = subsequent, S = sequela.",
    guidelines: ["7th character required: A (initial), D (subsequent), S (sequela)"],
    laterality: "none",
  },
  {
    code: "S82.001A",
    description: "Unspecified fracture of right patella, closed, initial",
    chapter: "Injury",
    category: "Fracture",
    medicareRate: 128.50,
    commercialRate: 245.00,
    notes: "Right patella fracture, closed. Use specific fracture type when known.",
    laterality: "right",
  },

  // ─── Neoplasms ──────────────────────────────────────────────────
  {
    code: "C50.911",
    description: "Malignant neoplasm of unspecified site of right female breast",
    chapter: "Neoplasms",
    category: "Breast cancer",
    medicareRate: 185.40,
    commercialRate: 350.00,
    notes: "Right breast. Subtype (ductal, lobular) and laterality matter. Use N60-N65 for benign.",
    laterality: "right",
  },
  {
    code: "Z12.31",
    description: "Encounter for screening mammogram for malignant neoplasm of breast",
    chapter: "Z Codes",
    category: "Cancer screening",
    medicareRate: 42.00,
    commercialRate: 82.00,
    notes: "Routine screening mammogram. Age 40+ recommended annually.",
    laterality: "none",
  },
  {
    code: "D63.0",
    description: "Anemia in neoplastic disease",
    chapter: "Blood",
    category: "Anemia",
    medicareRate: 55.20,
    commercialRate: 105.00,
    notes: "Code first neoplasm (C00-D49). Anemia due to chemotherapy or cancer.",
    codeFirst: "Code neoplasm first (C00-D49)",
    laterality: "none",
  },
];

export function searchICD10(query: string): ICD10Code[] {
  if (!query || query.length < 1) return ICD10_CODES.slice(0, 15);
  const q = query.toLowerCase();
  return ICD10_CODES.filter(
    (c) =>
      c.code.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.chapter.toLowerCase().includes(q) ||
      c.category.toLowerCase().includes(q)
  );
}
